const mongoose = require('mongoose'),
Lyric = mongoose.model('Lyric');

exports.get_lyrics = function(req, res) {
  Lyric.find({}, function(err, lyric) {
    if (err)
      res.send(err);
    res.json(lyric);
  });
};

exports.seed_lyrics = function(req, res) {
  const lyrics = [
    { lyric_order: 1, song: 'look at me now', duration: 3.0, content: "Cause I'm feelin like I'm runnin And I'm feelin like I gotta get away get away get away" },
    { lyric_order: 2, song: 'look at me now', duration: 3.3, content: "Better know that I don't and I won't ever stop Cause you know I gotta win everydayday" },
    { lyric_order: 3, song: 'look at me now', duration: 3.2, content: "See they really really wanna pop me Just know that you will never flop me" },
    { lyric_order: 4, song: 'look at me now', duration: 3.1, content: "And I know that I can be a little cocky You ain't never gonna stop me" },
    { lyric_order: 5, song: 'look at me now', duration: 2.8, content: "Everytime I come gotta set it Then I gotta go and then I gotta get it" },
    { lyric_order: 6, song: 'look at me now', duration: 2.8, content: "Then I gotta blow and then I gotta show that Any little thing that think that he be doin" },
    { lyric_order: 7, song: 'look at me now', duration: 1.4, content: "Cause it doesn't matter cause I'm gonna dadadada" },
    { lyric_order: 8, song: 'look at me now', duration: 3.0, content: "Then I'm gonna murder everything and anything A badaboom a badabing I gotta do a lotta things" },
    { lyric_order: 9, song: 'look at me now', duration: 3.7, content: "That make it clearer to a couple That I always win and then I gotta get it again And again and then again" },
    { lyric_order: 10, song: 'look at me now', duration: 2.9, content: "And I be doin it to death And now I move a little foul better call a ref" },
    { lyric_order: 11, song: 'look at me now', duration: 3.3, content: "And everybody know my style And know that I'm the best When it come to doing this and I be bangin on my chest" },
    { lyric_order: 12, song: 'look at me now', duration: 2.9, content: "And I bang in the East and I'm bangin in the West And I come to give you more and I will never give you less" },
    { lyric_order: 13, song: 'look at me now', duration: 3.5, content: "You will hear it in the street or you could read it in the press Do you really wanna know whats next let's go" },
    { lyric_order: 14, song: 'look at me now', duration: 3.2, content: "See the way we on and then we all up in the race And you know we gotta go Don't try to keep up with the pace" },
    { lyric_order: 15, song: 'look at me now', duration: 3.3, content: "And we strugglin and hustlin and sendin in and gettin in And we always gotta do it take it to another place" },
    { lyric_order: 16, song: 'look at me now', duration: 3.3, content: "Gotta taste it and I gotta grab it And I gotta cut all through this traffic" },
    { lyric_order: 17, song: 'look at me now', duration: 100.0, content: "Just to be at the top of the throne better know I gotta have it" },
    { lyric_order: 1, song: 'roar', duration: 5.2, content: "I used to bite my tongue and hold my breath Scared to rock the boat and make a mess" },
    { lyric_order: 2, song: 'roar', duration: 5.3, content: "So I sat quietly agreed politely" },
    { lyric_order: 3, song: 'roar', duration: 5.4, content: "I guess that I forgot I had a choice I let you push me past the breaking point" },
    { lyric_order: 4, song: 'roar', duration: 11.6, content: "I stood for nothing so I fell for everything" },
    { lyric_order: 5, song: 'roar', duration: 5.2, content: "You held me down but I got up Already brushing off the dust" },
    { lyric_order: 6, song: 'roar', duration: 5.6, content: "You hear my voice you hear that sound Like thunder gonna shake your ground" },
    { lyric_order: 7, song: 'roar', duration: 5.2, content: "You held me down but I got up Get ready cause I've had enough" },
    { lyric_order: 8, song: 'roar', duration: 3.0, content: "I see it all I see it now" },
    { lyric_order: 9, song: 'roar', duration: 4.5, content: "I got the eye of the tiger a fighter" },
    { lyric_order: 10, song: 'roar', duration: 5.5, content: "dancing through the fire Cause I am a champion" },
    { lyric_order: 11, song: 'roar', duration: 8.0, content: "and you're gonna hear me roar Louder louder than a lion" },
    { lyric_order: 12, song: 'roar', duration: 3.0, content: "Cause I am a champion" },
    { lyric_order: 13, song: 'roar', duration: 16.3, content: "and you're gonna hear me roar Oh oh oh oh oh oh You're gonna hear me roar" },
    { lyric_order: 14, song: 'roar', duration: 5.4, content: "Now I'm floating like a butterfly Stinging like a bee I earned my stripes" },
    { lyric_order: 15, song: 'roar', duration: 5.1, content: "I went from zero to my own hero" },
    { lyric_order: 16, song: 'roar', duration: 5.2, content: "You held me down but I got up Already brushing off the dust" },
    { lyric_order: 17, song: 'roar', duration: 5.0, content: "You hear my voice your hear that sound Like thunder gonna shake your ground" },
    { lyric_order: 18, song: 'roar', duration: 5.5, content: "You held me down but I got up Get ready cause I've had enough" },
    { lyric_order: 19, song: 'roar', duration: 3.0, content: "I see it all I see it now" },
    { lyric_order: 20, song: 'roar', duration: 4.5, content: "I got the eye of the tiger a fighter" },
    { lyric_order: 21, song: 'roar', duration: 5.5, content: "dancing through the fire cause I am a champion" },
    { lyric_order: 22, song: 'roar', duration: 8.0, content: "and you're gonna hear me roar Louder louder than a lion" },
    { lyric_order: 23, song: 'roar', duration: 3.0, content: "cause I am a champion" },
    { lyric_order: 24, song: 'roar', duration: 21.5, content: "and you're gonna hear me roar Oh oh oh oh oh oh You're gonna hear me roar Oh oh oh oh oh oh" },
    { lyric_order: 25, song: 'roar', duration: 19.0, content: "You're gonna hear me roar" },
    { lyric_order: 26, song: 'roar', duration: 4.5, content: "I got the eye of the tiger a fighter" },
    { lyric_order: 27, song: 'roar', duration: 5.5, content: "dancing through the fire Cause I am a champion" },
    { lyric_order: 28, song: 'roar', duration: 8.0, content:  "and you're gonna hear me roar Louder louder than a lion" },
    { lyric_order: 29, song: 'roar', duration: 3.0, content: "Cause I am a champion" },
    { lyric_order: 30, song: 'roar', duration: 21.0, content: "and you're gonna hear me roar Oh oh oh oh oh oh You're gonna hear me roar Oh oh oh oh oh oh" },
    { lyric_order: 31, song: 'roar', duration: 100.0, content: "You're gonna hear me roar" },
    { lyric_order: 1, song: "what a wonderful world", duration: 4.7, content: "I see trees of green" },
     { lyric_order: 2, song: "what a wonderful world", duration: 6.78, content: "red roses too I see them bloom" },
     { lyric_order: 3, song: "what a wonderful world", duration: 6.94, content: "for me and you And I think to myself" },
     { lyric_order: 4, song: "what a wonderful world", duration: 8.04, content: "what a wonderful world" },
     { lyric_order: 5, song: "what a wonderful world", duration: 4.54, content: "I see skies of blue" },
     { lyric_order: 6, song: "what a wonderful world", duration: 3.4, content: "and clouds of white" },
     { lyric_order: 7, song: "what a wonderful world", duration: 2.22, content: "The bright blessed day" },
     { lyric_order: 8, song: "what a wonderful world", duration: 3.72, content: "the dark sacred night" },
     { lyric_order: 9, song: "what a wonderful world", duration: 4.92, content: "And I think to myself" },
     { lyric_order: 10, song: "what a wonderful world", duration: 8.09, content: "what a wonderful world" },
     { lyric_order: 11, song: "what a wonderful world", duration: 6.65, content: "The colors of the rainbow so pretty in the sky" },
     { lyric_order: 12, song: "what a wonderful world", duration: 5.78, content: "Are also on the faces of people going by" },
     { lyric_order: 13, song: "what a wonderful world", duration: 8.6, content: "I see friends shaking hands saying how do you do" },
     { lyric_order: 14, song: "what a wonderful world", duration: 5.8, content: "Theyre really saying I love you" },
     { lyric_order: 15, song: "what a wonderful world", duration: 4.42, content: "I hear babies crying" },
     { lyric_order: 16, song: "what a wonderful world", duration: 3.52, content: "I watch them grow" },
     { lyric_order: 17, song: "what a wonderful world", duration: 2.22, content: "Theyll learn much more" },
     { lyric_order: 18, song: "what a wonderful world", duration: 3.08, content: "than Ill ever know" },
     { lyric_order: 19, song: "what a wonderful world", duration: 5.08, content: "And I think to myself" },
     { lyric_order: 20, song: "what a wonderful world", duration: 6.38, content: "what a wonderful world" },
     { lyric_order: 21, song: "what a wonderful world", duration: 7.56, content: "Yes I think to myself" },
     { lyric_order: 22, song: "what a wonderful world", duration: 2.56, content: "what a wonderful world" },
     { lyric_order: 1, song: "everlong", duration: 2.42, content: "Hello"},
      { lyric_order: 2, song: "everlong", duration: 4.48, content: "Ive waited here for you"},
      { lyric_order: 3, song: "everlong", duration: 3.66, content: "everlong"},
      { lyric_order: 4, song: "everlong", duration: 2.56, content: "Tonight"},
      { lyric_order: 5, song: "everlong", duration: 4.0, content: "I throw myself into"},
      { lyric_order: 6, song: "everlong", duration: 14.68, content: "And out of the red Out of her head she sang"},
      { lyric_order: 7, song: "everlong", duration: 6.94, content: "Come down And waste away with me"},
      { lyric_order: 8, song: "everlong", duration: 3.6, content: "down with me"},
      { lyric_order: 9, song: "everlong", duration: 6.86, content: "Slow how You wanted it to be"},
      { lyric_order: 10, song: "everlong", duration: 7.92, content: "Im over my head Out of her head she sang"},
      { lyric_order: 11, song: "everlong", duration: 4.18, content: "And I wonder"},
      { lyric_order: 12, song: "everlong", duration: 4.1, content: "When I sing along with you"},
      { lyric_order: 13, song: "everlong", duration: 6.1, content: "If everything could ever feel this real forever"},
      { lyric_order: 14, song: "everlong", duration: 6.04, content: "If anything could ever be this good again"},
      { lyric_order: 15, song: "everlong", duration: 3.26, content: "The only thing Ill ever ask of you"},
      { lyric_order: 16, song: "everlong", duration: 16.34, content: "You gotta promise not to stop when I say when she sang"},
      { lyric_order: 17, song: "everlong", duration: 2.34, content: "Breathe out"},
      { lyric_order: 18, song: "everlong", duration: 4.42, content: "so I can breathe you in"},
      { lyric_order: 19, song: "everlong", duration: 3.78, content: "Hold you in"},
      { lyric_order: 20, song: "everlong", duration: 2.52, content: "And now"},
      { lyric_order: 21, song: "everlong", duration: 4.44, content: "I know youve always been"},
      { lyric_order: 22, song: "everlong", duration: 7.78, content: "Out of your head Out of my head I sang"},
      { lyric_order: 23, song: "everlong", duration: 4.14, content: "And I wonder"},
      { lyric_order: 24, song: "everlong", duration: 4.2, content: "When I sing along with you"},
      { lyric_order: 25, song: "everlong", duration: 6.08, content: "If everything could ever feel this real forever"},
      { lyric_order: 26, song: "everlong", duration: 6.04, content: "If anything could ever be this good again"},
      { lyric_order: 27, song: "everlong", duration: 3.12, content: "The only thing Ill ever ask of you"},
      { lyric_order: 28, song: "everlong", duration: 32.18, content: "You gotta promise not to stop when I say when she sang"},
      { lyric_order: 29, song: "everlong", duration: 4.24, content: "And I wonder"},
      { lyric_order: 30, song: "everlong", duration: 5.94, content: "If everything could ever feel this real forever"},
      { lyric_order: 31, song: "everlong", duration: 6.08, content: "If anything could ever be this good again"},
      { lyric_order: 32, song: "everlong", duration: 3.18, content: "The only thing Ill ever ask of you"},
      { lyric_order: 33, song: "everlong", duration: 4.18, content: "Youve got to promise not to stop when I say when"},
      { lyric_order: 1, song: "gangster paradise", duration: 2.64, content: "As I walk through the valley of the shadow of death"},
      { lyric_order: 2, song: "gangster paradise", duration: 3.6, content: "I take a look at my life and realize theres nothing left"},
      { lyric_order: 3, song: "gangster paradise", duration: 3.0, content: "cause I been blasting and laughing so long that"},
      { lyric_order: 4, song: "gangster paradise", duration: 2.54, content: "even my momma thinks that my mind is gone"},
      { lyric_order: 5, song: "gangster paradise", duration: 2.8, content: "But I aint never crossed a man that didnt deserve it"},
      { lyric_order: 6, song: "gangster paradise", duration: 3.28, content: "Me be treated like a punk You know thats unheard of"},
      { lyric_order: 7, song: "gangster paradise", duration: 3.24, content: "You better watch out your talkin and where your walkin"},
      { lyric_order: 8, song: "gangster paradise", duration: 2.68, content: "Or you and your homies might be lined in chalk"},
      { lyric_order: 9, song: "gangster paradise", duration: 3.04, content: "I really hate to trip but I gotta tho"},
      { lyric_order: 10, song: "gangster paradise", duration: 3.46, content: "as they cope I see myself in the pistol smoke Fool"},
      { lyric_order: 11, song: "gangster paradise", duration: 2.8, content: "Im the kinda gee the little homies wanna be like"},
      { lyric_order: 12, song: "gangster paradise", duration: 3.2, content: "On my knees in the night saying prayers in the street light"},
      { lyric_order: 13, song: "gangster paradise", duration: 6.07, content: "Weve been spending most our lives livin in a gangsters paradise"},
      { lyric_order: 14, song: "gangster paradise", duration: 6.07, content: "Weve been spending most our lives livin in a gangsters paradise"},
      { lyric_order: 15, song: "gangster paradise", duration: 6.0, content: "We keep spending most our lives livin in a gangsters paradise"},
      { lyric_order: 16, song: "gangster paradise", duration: 6.0, content: "We keep spending most our lives livin in a gangsters paradise"},
      { lyric_order: 17, song: "gangster paradise", duration: 2.64, content: "Look at the situation they got me facin"},
      { lyric_order: 18, song: "gangster paradise", duration: 3.12, content: "I cant live a normal life I was raised by the street"},
      { lyric_order: 19, song: "gangster paradise", duration: 2.32, content: "So I gotta be down with the hood team"},
      { lyric_order: 20, song: "gangster paradise", duration: 3.34, content: "Too much television watchin got me chasing dreams"},
      { lyric_order: 21, song: "gangster paradise", duration: 2.96, content: "Im an educated fool with money on my mind"},
      { lyric_order: 22, song: "gangster paradise", duration: 3.0, content: "Got my ten in my hand and a gleam in my eye"},
      { lyric_order: 23, song: "gangster paradise", duration: 2.8, content: "Im a locd out gangsta set trippin banger"},
      { lyric_order: 24, song: "gangster paradise", duration: 3.4, content: "And my homies is down so dont arouse my anger fool"},
      { lyric_order: 25, song: "gangster paradise", duration: 3.0, content: "Death aint nothing but a heartbeat away"},
      { lyric_order: 26, song: "gangster paradise", duration: 3.6, content: "Im living life Do or die What can I say"},
      { lyric_order: 27, song: "gangster paradise", duration: 2.2, content: "Im 23 now But will I live to see 24?"},
      { lyric_order: 28, song: "gangster paradise", duration: 2.8, content: "The way things is goin I dont know"},
      { lyric_order: 29, song: "gangster paradise", duration: 5.6, content: "Tell me why are we so blind to see"},
      { lyric_order: 30, song: "gangster paradise", duration: 6.7, content: "That the ones we hurt are you and me"},
      { lyric_order: 31, song: "gangster paradise", duration: 6.15, content: "Weve been spending most our lives livin in a gangsters paradise"},
      { lyric_order: 32, song: "gangster paradise", duration: 6.15, content: "Weve been spending most our lives livin in a gangsters paradise"},
      { lyric_order: 33, song: "gangster paradise", duration: 6.0, content: "We keep spending most our lives livin in a gangsters paradise"},
      { lyric_order: 34, song: "gangster paradise", duration: 6.0, content: "We keep spending most our lives livin in a gangsters paradise"},
      { lyric_order: 35, song: "gangster paradise", duration: 3.1, content: "Power and the money Money and the power"},
      { lyric_order: 36, song: "gangster paradise", duration: 3.1, content: "Minute after minute Hour after hour"},
      { lyric_order: 37, song: "gangster paradise", duration: 3.1, content: "Everybodys running but half of them aint living"},
      { lyric_order: 38, song: "gangster paradise", duration: 3.1, content: "Whats going on in the kitchen but I dont know whats cooking"},
      { lyric_order: 39, song: "gangster paradise", duration: 3.0, content: "They say I gotta learn but no ones here to teach me"},
      { lyric_order: 40, song: "gangster paradise", duration: 3.2, content: "If they cant understand it How can they teach me"},
      { lyric_order: 41, song: "gangster paradise", duration: 2.1, content: "I guess they cant I guess they wont"},
      { lyric_order: 42, song: "gangster paradise", duration: 3.9, content: "I guess the front Thats how I know my life is outta luck fool"},
      { lyric_order: 43, song: "gangster paradise", duration: 6.0, content: "Weve been spending most our lives livin in a gangsters paradise"},
      { lyric_order: 44, song: "gangster paradise", duration: 6.0, content: "Weve been spending most our lives livin in a gangsters paradise"},
      { lyric_order: 45, song: "gangster paradise", duration: 5.8, content: "We keep spending most our lives livin in a gangsters paradise"},
      { lyric_order: 46, song: "gangster paradise", duration: 5.8, content: "We keep spending most our lives livin in a gangsters paradise"},
      { lyric_order: 47, song: "gangster paradise", duration: 5.4, content: "Tell me why are we so blind to see"},
      { lyric_order: 48, song: "gangster paradise", duration: 6.3, content: "That the ones we hurt are you and me"},
      { lyric_order: 49, song: "gangster paradise", duration: 5.8, content: "Tell me why are we so blind to see"},
      { lyric_order: 50, song: "gangster paradise", duration: 6.02, content: "That the ones we hurt are you and me"}
  ];

  for(let lyric of lyrics){
    const newLyric = new Lyric(lyric);
    newLyric.save();
  }

  res.send('Database seeded!')
}
